### ISSUE TITLE
Run test fail on windows

### ISSUE THREAD

**Issue by tanpv** [PolymathNetwork/polymath-core#293]
I clone whole repository then checkout to dev branch development-1.5.0
Then run the test with command "truffle test .\test\l_percentage_transfer_manager.js"
And only get 3 cases pass as log follow. Please help

 `Generate the SecurityToken
      √ Should register the ticker before the generation of the security token (155ms)
      1) Should generate the new security token with the same symbol as registered above

    Events emitted during test:
    ---------------------------

    Approval(owner: <indexed>, spender: <indexed>, value: 250000000000000000000)

    ---------------------------
      2) Should intialize the auto attached modules
    > No events were emitted
    Buy tokens using on-chain whitelist
      3) Should Buy the tokens
    > No events were emitted
      4) Should Buy some more tokens
    > No events were emitted
       tx -> failed because Token is not paid
      5) Should successfully attach the PercentageTransferManagerr factory with the security token

    Events emitted during test:
    ---------------------------

    Transfer(from: <indexed>, to: <indexed>, value: 500000000000000000000)

    ---------------------------
      6) Should successfully attach the PercentageTransferManager factory with the security token
    > No events were emitted
      7) Should successfully attach the PercentageTransferManager with the security token
    > No events were emitted
      8) Add a new token holder
    > No events were emitted
      9) Should pause the tranfers at transferManager level
    > No events were emitted
      10) Should still be able to transfer between existing token holders up to limit
    > No events were emitted
      11) Should unpause the tranfers at transferManager level
    > No events were emitted
         tx revert -> Too many holders
      12) Should not be able to transfer between existing token holders over limit
    > No events were emitted
      13) Modify holder percentage to 100
    > No events were emitted
      14) Should be able to transfer between existing token holders up to limit
    > No events were emitted
      15) Should be able to whitelist address and then transfer regardless of holders
    > No events were emitted
      16) Should get the permission
    > No events were emitted
    Percentage Transfer Manager Factory test cases
      √ Should get the exact details of the factory (81ms)
      √ Should get the tags of the factory

  3 passing (3s)
  16 failing

  1) Contract: PercentageTransferManager
       Generate the SecurityToken
         Should generate the new security token with the same symbol as registered above:
     Error: Exceeds block gas limit
      at Object.InvalidResponse (C:\Users\TAN\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\errors.js:38:1)
      at C:\Users\TAN\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\requestmanager.js:86:1
      at C:\Users\TAN\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-provider\wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (C:\Users\TAN\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\TAN\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (C:\Users\TAN\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (C:\Users\TAN\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:509:1)
      at IncomingMessage.<anonymous> (C:\Users\TAN\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  2) Contract: PercentageTransferManager
       Generate the SecurityToken
         Should intialize the auto attached modules:
     TypeError: Cannot read property 'modules' of undefined
      at _callee4$ (C:/polymath-core/test/l_percentage_transfer_manager.js:271:51)
      at tryCatch (node_modules\regenerator-runtime\runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules\regenerator-runtime\runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules\regenerator-runtime\runtime.js:117:21)
      at step (test\l_percentage_transfer_manager.js:17:191)
      at test\l_percentage_transfer_manager.js:17:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test\l_percentage_transfer_manager.js:17:99)

  3) Contract: PercentageTransferManager
       Buy tokens using on-chain whitelist
         Should Buy the tokens:
     TypeError: Cannot read property 'modifyWhitelist' of undefined
      at _callee6$ (C:/polymath-core/test/l_percentage_transfer_manager.js:283:53)
      at tryCatch (node_modules\regenerator-runtime\runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules\regenerator-runtime\runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules\regenerator-runtime\runtime.js:117:21)
      at step (test\l_percentage_transfer_manager.js:17:191)
      at test\l_percentage_transfer_manager.js:17:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test\l_percentage_transfer_manager.js:17:99)

  4) Contract: PercentageTransferManager
       Buy tokens using on-chain whitelist
         Should Buy some more tokens:
     TypeError: Cannot read property 'modifyWhitelist' of undefined
      at _callee7$ (C:/polymath-core/test/l_percentage_transfer_manager.js:311:53)
      at tryCatch (node_modules\regenerator-runtime\runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules\regenerator-runtime\runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules\regenerator-runtime\runtime.js:117:21)
      at step (test\l_percentage_transfer_manager.js:17:191)
      at test\l_percentage_transfer_manager.js:17:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test\l_percentage_transfer_manager.js:17:99)

  5) Contract: PercentageTransferManager
       Buy tokens using on-chain whitelist
         Should successfully attach the PercentageTransferManagerr factory with the security token:
     AssertionError: TypeError: Cannot read property 'addModule' of undefined
      at ensureException (C:/polymath-core/test/helpers/utils.js:11:5)
      at _callee8$ (C:/polymath-core/test/l_percentage_transfer_manager.js:340:17)
      at tryCatch (node_modules\regenerator-runtime\runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules\regenerator-runtime\runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules\regenerator-runtime\runtime.js:117:21)
      at step (test\l_percentage_transfer_manager.js:17:191)
      at test\l_percentage_transfer_manager.js:17:361
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  6) Contract: PercentageTransferManager
       Buy tokens using on-chain whitelist
         Should successfully attach the PercentageTransferManager factory with the security token:
     TypeError: Cannot read property 'address' of undefined
      at _callee9$ (C:/polymath-core/test/l_percentage_transfer_manager.js:348:56)
      at tryCatch (node_modules\regenerator-runtime\runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules\regenerator-runtime\runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules\regenerator-runtime\runtime.js:117:21)
      at step (test\l_percentage_transfer_manager.js:17:191)
      at test\l_percentage_transfer_manager.js:17:361
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  7) Contract: PercentageTransferManager
       Buy tokens using on-chain whitelist
         Should successfully attach the PercentageTransferManager with the security token:
     TypeError: Cannot read property 'addModule' of undefined
      at _callee10$ (C:/polymath-core/test/l_percentage_transfer_manager.js:362:46)
      at tryCatch (node_modules\regenerator-runtime\runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules\regenerator-runtime\runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules\regenerator-runtime\runtime.js:117:21)
      at step (test\l_percentage_transfer_manager.js:17:191)
      at test\l_percentage_transfer_manager.js:17:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test\l_percentage_transfer_manager.js:17:99)

  8) Contract: PercentageTransferManager
       Buy tokens using on-chain whitelist
         Add a new token holder:
     TypeError: Cannot read property 'modifyWhitelist' of undefined
      at _callee11$ (C:/polymath-core/test/l_percentage_transfer_manager.js:375:53)
      at tryCatch (node_modules\regenerator-runtime\runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules\regenerator-runtime\runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules\regenerator-runtime\runtime.js:117:21)
      at step (test\l_percentage_transfer_manager.js:17:191)
      at test\l_percentage_transfer_manager.js:17:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test\l_percentage_transfer_manager.js:17:99)

  9) Contract: PercentageTransferManager
       Buy tokens using on-chain whitelist
         Should pause the tranfers at transferManager level:
     TypeError: Cannot read property 'pause' of undefined
      at _callee12$ (C:/polymath-core/test/l_percentage_transfer_manager.js:399:56)
      at tryCatch (node_modules\regenerator-runtime\runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules\regenerator-runtime\runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules\regenerator-runtime\runtime.js:117:21)
      at step (test\l_percentage_transfer_manager.js:17:191)
      at test\l_percentage_transfer_manager.js:17:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test\l_percentage_transfer_manager.js:17:99)

  10) Contract: PercentageTransferManager
       Buy tokens using on-chain whitelist
         Should still be able to transfer between existing token holders up to limit:
     TypeError: Cannot read property 'transfer' of undefined
      at _callee13$ (C:/polymath-core/test/l_percentage_transfer_manager.js:405:35)
      at tryCatch (node_modules\regenerator-runtime\runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules\regenerator-runtime\runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules\regenerator-runtime\runtime.js:117:21)
      at step (test\l_percentage_transfer_manager.js:17:191)
      at test\l_percentage_transfer_manager.js:17:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test\l_percentage_transfer_manager.js:17:99)

  11) Contract: PercentageTransferManager
       Buy tokens using on-chain whitelist
         Should unpause the tranfers at transferManager level:
     TypeError: Cannot read property 'unpause' of undefined
      at _callee14$ (C:/polymath-core/test/l_percentage_transfer_manager.js:414:47)
      at tryCatch (node_modules\regenerator-runtime\runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules\regenerator-runtime\runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules\regenerator-runtime\runtime.js:117:21)
      at step (test\l_percentage_transfer_manager.js:17:191)
      at test\l_percentage_transfer_manager.js:17:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test\l_percentage_transfer_manager.js:17:99)

  12) Contract: PercentageTransferManager
       Buy tokens using on-chain whitelist
         Should not be able to transfer between existing token holders over limit:
     AssertionError: TypeError: Cannot read property 'transfer' of undefined
      at ensureException (C:/polymath-core/test/helpers/utils.js:11:5)
      at _callee15$ (C:/polymath-core/test/l_percentage_transfer_manager.js:423:17)
      at tryCatch (node_modules\regenerator-runtime\runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules\regenerator-runtime\runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules\regenerator-runtime\runtime.js:117:21)
      at step (test\l_percentage_transfer_manager.js:17:191)
      at test\l_percentage_transfer_manager.js:17:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test\l_percentage_transfer_manager.js:17:99)

  13) Contract: PercentageTransferManager
       Buy tokens using on-chain whitelist
         Modify holder percentage to 100:
     TypeError: Cannot read property 'changeHolderPercentage' of undefined
      at _callee16$ (C:/polymath-core/test/l_percentage_transfer_manager.js:432:47)
      at tryCatch (node_modules\regenerator-runtime\runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules\regenerator-runtime\runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules\regenerator-runtime\runtime.js:117:21)
      at step (test\l_percentage_transfer_manager.js:17:191)
      at test\l_percentage_transfer_manager.js:17:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test\l_percentage_transfer_manager.js:17:99)

  14) Contract: PercentageTransferManager
       Buy tokens using on-chain whitelist
         Should be able to transfer between existing token holders up to limit:
     TypeError: Cannot read property 'modifyWhitelist' of undefined
      at _callee17$ (C:/polymath-core/test/l_percentage_transfer_manager.js:441:47)
      at tryCatch (node_modules\regenerator-runtime\runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules\regenerator-runtime\runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules\regenerator-runtime\runtime.js:117:21)
      at step (test\l_percentage_transfer_manager.js:17:191)
      at test\l_percentage_transfer_manager.js:17:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test\l_percentage_transfer_manager.js:17:99)

  15) Contract: PercentageTransferManager
       Buy tokens using on-chain whitelist
         Should be able to whitelist address and then transfer regardless of holders:
     TypeError: Cannot read property 'changeHolderPercentage' of undefined
      at _callee18$ (C:/polymath-core/test/l_percentage_transfer_manager.js:446:45)
      at tryCatch (node_modules\regenerator-runtime\runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules\regenerator-runtime\runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules\regenerator-runtime\runtime.js:117:21)
      at step (test\l_percentage_transfer_manager.js:17:191)
      at test\l_percentage_transfer_manager.js:17:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test\l_percentage_transfer_manager.js:17:99)

  16) Contract: PercentageTransferManager
       Buy tokens using on-chain whitelist
         Should get the permission:
     TypeError: Cannot read property 'getPermissions' of undefined
      at _callee19$ (C:/polymath-core/test/l_percentage_transfer_manager.js:452:58)
      at tryCatch (node_modules\regenerator-runtime\runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules\regenerator-runtime\runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules\regenerator-runtime\runtime.js:117:21)
      at step (test\l_percentage_transfer_manager.js:17:191)
      at test\l_percentage_transfer_manager.js:17:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test\l_percentage_transfer_manager.js:17:99)`

**Comment by satyamakgec** [comment]
Hey @tanpv, How do you run the `ganache-cli` on your local system? Please use this command to run the ganache - `npm run ganache-cli`.  The reason is custom block gas limit

**Comment by tanpv** [comment]
Thanks @satyamakgec , Your solution work.
