### ISSUE TITLE
New STO modules can not be attached in polymath-core-dev-3.0.0 .

### ISSUE THREAD

**Issue by YukinoriHamada** [PolymathNetwork/polymath-core#787]
I want to "Add new STO module". I had done several commands but finally Error happed. Why? Please tell me correct inputs that I should enter. I think that  in `Enter a label to help you to identify this module: `  What kind of labels I must enter is unclear .

```
What type of STO do you want? [1, 2, 0]: 2
Selected: USDTieredSTO 

Launch STO - USD pegged tiered STO
Enter P for POLY raise, S for Stable Coin raise, E for Ether raise or any combination of them (i.e. PSE for all): E
Enter the address that will receive the funds from the STO (0x4117C71214ac397AEDd6c14ba2288Abd9A5823b8): 0x4117C71214ac397AEDd6c14ba2288Abd9A5823b8
Enter the address that will receive remaining tokens in the case the cap is not met (0x4117C71214ac397AEDd6c14ba2288Abd9A5823b8): 0x4117C71214ac397AEDd6c14ba2288Abd9A5823b8
Enter the number of tiers for the STO? (3): 3
How many tokens do you plan to sell on tier No. 1? (190000000): 190000000
What is the USD per token rate for tier No. 1? (0.05): 0.05
How many tokens do you plan to sell on tier No. 2? (100000000): 100000000
What is the USD per token rate for tier No. 2? (0.10): 0.10
How many tokens do you plan to sell on tier No. 3? (200000000): 200000000
What is the USD per token rate for tier No. 3? (0.15): 0.15
What is the minimum investment in USD? (5): 5
What is the default limit for non accredited investors in USD? (2500): 2500
Enter the start time for the STO (Unix Epoch time)
(1 minutes from now = 1565575079 ): 1565575079
Enter the end time for the STO (Unix Epoch time)
(1 month from now = 1568167025 ): 1568167025
Do you want to add this module archived? [y/n]: y
Enter a label to help you to identify this module: 
---- Transaction executed: transfer - Gas limit provided: 72994 ----

Your transaction is being processed. Please wait...
TxHash: 0x865cc99878885489f245523899a7d68889cbd56435c48dea4b0deba20806c82f

Congratulations! The transaction was successfully completed.
Gas used: 36497 - Gas spent: 0.00182485 Ether
Review it on Etherscan.
TxHash: 0x865cc99878885489f245523899a7d68889cbd56435c48dea4b0deba20806c82f

Number of POLY sent: 80000
(node:22354) UnhandledPromiseRejectionWarning: Error: Given parameter bytes has an invalid length: "0x0"
    at SolidityTypeBytes.formatInputBytes [as _inputFormatter] (/Users/hamadayukinori/polymath@3.0.0/CLI/node_modules/web3-eth-abi/src/formatters.js:62:15)
    at SolidityTypeBytes.SolidityType.encode (/Users/hamadayukinori/polymath@3.0.0/CLI/node_modules/web3-eth-abi/src/type.js:188:17)
    at /Users/hamadayukinori/polymath@3.0.0/CLI/node_modules/web3-eth-abi/src/index.js:255:29
    at Array.map (<anonymous>)
    at ABICoder.encodeParameters (/Users/hamadayukinori/polymath@3.0.0/CLI/node_modules/web3-eth-abi/src/index.js:254:34)
    at /Users/hamadayukinori/polymath@3.0.0/CLI/node_modules/web3-eth-contract/src/index.js:425:24
    at Array.map (<anonymous>)
    at Object._encodeMethodABI (/Users/hamadayukinori/polymath@3.0.0/CLI/node_modules/web3-eth-contract/src/index.js:424:12)
    at Object._processExecuteArguments (/Users/hamadayukinori/polymath@3.0.0/CLI/node_modules/web3-eth-contract/src/index.js:740:39)
    at Object._executeMethod (/Users/hamadayukinori/polymath@3.0.0/CLI/node_modules/web3-eth-contract/src/index.js:765:54)
    at getGasLimit (/Users/hamadayukinori/polymath@3.0.0/CLI/commands/common/common_functions.js:163:55)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:22354) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22354) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by YukinoriHamada** [comment]
I solve above problem!
I should enter Large character (eg, `A`) in `Enter a label to help you to identify this module: ` , then I got CappedSTO deployed!

**Comment by VictorVicente** [comment]
Thank you @YukinoriHamada for reporting this problem. I'll fix it avoiding an empty input for the module label.
